"""Build RAG_content_heroes.json without API calls.
Reads pos_data.json for position info, uses hardcoded guide text.
Run: python scripts/build_hero_guides.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

with open(ROOT / "data/pos_data.json") as f:
    pos_data = json.load(f)
with open(ROOT / "data/hero_data.json") as f:
    _hero_data = json.load(f)
name_to_id = {h["displayName"]: hid for hid, h in _hero_data.items()}

POS_NAMES = {
    "1": "Carry (Pos 1)",
    "2": "Mid (Pos 2)",
    "3": "Offlane (Pos 3)",
    "4": "Soft Support (Pos 4)",
    "5": "Hard Support (Pos 5)",
}


def get_positions(hero_id):
    positions = []
    for pos_key, heroes in pos_data.items():
        entry = heroes.get(str(hero_id))
        if entry and entry["matchCount"] >= 50:
            wr = (
                round(entry["winCount"] / entry["matchCount"] * 100, 1)
                if entry["matchCount"] > 0
                else 0
            )
            positions.append(
                (
                    pos_key,
                    POS_NAMES.get(pos_key, f"Pos {pos_key}"),
                    wr,
                    entry["matchCount"],
                )
            )
    positions.sort(key=lambda x: x[3], reverse=True)
    return positions


# (goal, requires, fights, dont, timings, gameStage)
GUIDES = {
    "Anti-Mage": (
        "Farm fast with Blink mobility, burn mana, punish low-mana heroes with Mana Void.",
        "Free safe lane farm, Battlefury timing, team creating space.",
        "Blink onto backline casters, Counterspell key spells, Mana Void when enemy mana pools are low.",
        "Fight before BF+Manta, Blink into multiple heroes, skip BKB when needed.",
        "Battlefury 14-16min, Manta 22-24min. Fight once you have Abyssal Blade.",
        "Early: last hit in safe lane, avoid fights. Mid: split push with Blink, farm triangle+lanes. Late: pick off casters, Mana Void teamfights.",
    ),
    "Axe": (
        "Initiate fights with Blink+Call, force enemies to attack you, execute low HP heroes with Culling Blade.",
        "Blink Dagger timing, lane dominance with Counter Helix spins, Blade Mail synergy.",
        "Blink+Call multiple heroes, Blade Mail during Call, Culling Blade to reset and chase.",
        "Call without Blade Mail ready, initiate without team follow-up, get kited without Blink.",
        "Blink 10-12min, Blade Mail right after. BKB by 22-25min for reliable initiation.",
        "Early: dominate offlane with Counter Helix, cut waves. Mid: Blink initiation, pick-offs. Late: frontline initiator, Call priority targets.",
    ),
    "Bane": (
        "Lock down key targets with Fiend's Grip, set up kills with Nightmare, reduce damage with Enfeeble.",
        "Safe positioning for full Grip channel, Nightmare saves on allies, vision for catches.",
        "Grip the biggest threat, Nightmare secondary targets, Enfeeble enemy carry.",
        "Grip without team nearby, Nightmare allies in danger accidentally, waste Grip on supports.",
        "Aether Lens 15-18min for safe Grip range. Aghs Shard for AoE Brain Sap sustain.",
        "Early: harass with Brain Sap, set up kills with Nightmare. Mid: smoke and Grip priority targets. Late: Grip enemy carry in fights, save allies with Nightmare.",
    ),
    "Bloodseeker": (
        "Snowball with kills, sustain with Bloodrage, punish movement with Rupture.",
        "Early kills to snowball, Thirst vision to find low-HP heroes, lane dominance.",
        "Rupture mobile heroes, Bloodrage yourself for damage, Blood Rite for AoE silence.",
        "Chase too deep with Thirst, Rupture immobile heroes, fight without Bloodrage active.",
        "Maelstrom/Radiance 14-16min for farm acceleration. BKB timing critical.",
        "Early: dominate lane with Bloodrage sustain. Mid: gank with Thirst vision, Rupture kills. Late: Rupture key targets, provide Thirst vision for team.",
    ),
    "Crystal Maiden": (
        "Provide global mana regen with Arcane Aura, lockdown with Frostbite, teamfight with Freezing Field.",
        "Careful positioning (very slow, fragile), early jungle stacking, Frostbite catches.",
        "Stay back, Frostbite key targets, channel Freezing Field from fog or with BKB/Glimmer.",
        "Walk forward in fights (you die instantly), skip wards, use Freezing Field without protection.",
        "Glimmer Cape 15-18min for Freezing Field safety. BKB if snowballing.",
        "Early: roam for Frostbite kills, pull and stack camps. Mid: ward aggressively, smoke ganks. Late: stay alive in fights, Aura value scales.",
    ),
    "Drow Ranger": (
        "Win with Marksmanship armor ignoring attacks, dominate from range, push towers fast with aura.",
        "Maintain distance for Marksmanship (disabled when enemies close), team protection, high ground.",
        "Position far back, Gust to push divers away, Multishot for AoE. Marksmanship procs win sustained fights.",
        "Let gap-closers reach you, fight in tight spaces, skip Hurricane Pike.",
        "Dragon Lance 10-12min, Pike 16-18min. Aghs timing for Multishot power spike.",
        "Early: farm safe lane, harass with Frost Arrows. Mid: take towers with team, stay grouped. Late: siege high ground with range advantage, Gust key initiators.",
    ),
    "Earthshaker": (
        "Devastating teamfight with Echo Slam, block paths with Fissure, burst with Enchant Totem.",
        "Blink Dagger for initiation, Fissure accuracy, patience for multi-hero Echo Slams.",
        "Blink+Echo into clustered enemies, Fissure for stun chain, Totem for burst damage.",
        "Echo Slam on 1-2 heroes, Fissure block allies, initiate without Blink.",
        "Blink 14-18min (pos 4) or 10-12min (mid). Echo Slam fights won with 3+ targets.",
        "Early: roam with Fissure stuns, secure runes. Mid: Blink initiation timing. Late: wait for cluster, Echo Slam wins fights.",
    ),
    "Juggernaut": (
        "Reliable carry with Blade Fury magic immunity, Healing Ward sustain, Omnislash burst.",
        "Farm speed, Blade Fury kill potential early, Omnislash single-target isolation.",
        "Blade Fury to dodge spells, Healing Ward behind team, Omnislash isolated targets.",
        "Omnislash into creep waves, pop Blade Fury when you should be right-clicking, forget Healing Ward.",
        "Battlefury 14-15min or Maelstrom 11-12min. Aghs timing strong at 25min.",
        "Early: Blade Fury + support kills in lane, push tower. Mid: farm with cleave, take objectives. Late: Omnislash pick-offs, right-click carry with items.",
    ),
    "Mirana": (
        "Flexible hero — roam with Sacred Arrow stuns, Leap for mobility, Starfall burst.",
        "Arrow accuracy (5s stun at max range), team follow-up on arrows, flex pick advantage.",
        "Arrow priority targets from fog, Leap in/out, Starfall for burst. Moonlight Shadow for team invis ganks.",
        "Throw arrows without setup, Leap aggressively without escape plan, skip utility items.",
        "First core item 12-14min varies by role. Arrow+kill combos are the timing.",
        "Early: roam and arrow, secure kills with supports. Mid: push with team, arrow from trees. Late: utility/damage hybrid, Moonlight Shadow for positioning.",
    ),
    "Morphling": (
        "Shift between AGI (damage) and STR (survival), burst with Adaptive Strike, replicate enemy heroes.",
        "Farm for stat items, Morph management (don't get bursted while AGI), Linken's/Manta timing.",
        "Morph STR to survive burst, shift AGI to kill, Adaptive Strike for stun/nuke, Replicate for outplay.",
        "Full AGI morph against burst damage, fight without Morph shift available, replicate wrong hero.",
        "Ethereal Blade 18-20min for shotgun combo. Manta/Linken's for survivability.",
        "Early: farm safe lane, Waveform for last hits. Mid: Ethereal shotgun kills, farm aggressively. Late: stat-heavy carry, Replicate outplays.",
    ),
    "Shadow Fiend": (
        "Dominate mid with Razes, stack souls for damage, minus armor with Presence, Requiem burst.",
        "Win mid lane, maintain soul count, Raze accuracy, early tower pressure.",
        "Requiem in fights (or Eul's combo), Raze for damage/stacks, right-click with souls+items.",
        "Die and lose souls, miss Razes in fights, position for Requiem without BKB/setup.",
        "Eul's 12-13min for solo kill combo. BKB 18-20min. Desolator for physical build.",
        "Early: dominate mid with Razes, stack camps. Mid: take mid tower, rotate with Requiem. Late: high physical damage carry or magic burst build.",
    ),
    "Phantom Lancer": (
        "Overwhelm with illusions via Juxtapose, hard to pin down with Doppelganger. Illusions NERFED in 7.40 (no mana burn, reduced vision).",
        "Stat items to make illusions tanky (Diffusal no longer works on illusions), farm speed, Doppelganger usage.",
        "Send illusions in, find real PL positioning, Doppelganger to dodge/disjoint, overwhelm supports. New Illusory Armaments gives min damage floor.",
        "Buy Diffusal Blade — mana burn no longer works on illusions since 7.40. Avoid AoE-heavy matchups, don't fight before stat items.",
        "Heart/Skadi 22-25min for illusion tankiness. Manta Style for more illusions. Butterfly for AGI scaling. Weakened this patch.",
        "Early: farm safe lane, Phantom Edge for evasion. Mid: split push with illusions. Late: stat-heavy illusion army, but weaker than previous patches.",
    ),
    "Puck": (
        "Elusive mid with Phase Shift, initiate with Dream Coil, silence with Waning Rift.",
        "Phase Shift timing, Blink for initiation, Dream Coil on multiple heroes.",
        "Blink+Coil+Rift combo, Phase Shift dodges, Orb for escape/chase.",
        "Dream Coil one hero, Phase Shift too early, Orb aggressively without escape.",
        "Witch Blade/Eul's 12-14min. Blink 15-17min for Coil initiation.",
        "Early: win mid with Orb+Rift harass. Mid: gank with Coil, control tempo. Late: initiation and silence, elusive teamfighter.",
    ),
    "Pudge": (
        "Hook heroes out of position, Dismember to lock down, Rot for slow/damage, Flesh Heap tankiness.",
        "Hook accuracy, roaming timing, snowball with kills for Flesh Heap stacks.",
        "Hook priority targets, Dismember the carry/mid, Rot to slow in fights.",
        "Miss hooks and waste time, hook through creeps, Dismember without team nearby.",
        "Blink 15-18min for guaranteed Dismember. Aghs Shard for Rot buff.",
        "Early: roam from pos 4/5 or dominate mid. Mid: smoke+hook picks, Blink initiation. Late: tank with Flesh Heap stacks, hook key targets.",
    ),
    "Razor": (
        "Drain enemy damage with Static Link, run at people with speed, Eye of the Storm melts buildings.",
        "Get on top of link target, maintain link duration, BKB for uninterrupted link.",
        "Static Link enemy carry, run at them, Eye of the Storm for armor reduction, Plasma Field for AoE.",
        "Link supports instead of carry, break link early, fight without Eye of the Storm.",
        "BKB 16-18min for full link duration. Refresher for double Eye of the Storm.",
        "Early: win lane with Static Link pressure. Mid: push towers with Eye of the Storm. Late: drain carry damage, siege with team.",
    ),
    "Sand King": (
        "Initiate with Blink+Epicenter, Burrowstrike stun, Sandstorm for farming/invis.",
        "Blink for Epicenter initiation, channel time awareness, Caustic Finale for lane/farm.",
        "Blink+Epicenter from fog, Burrowstrike chain stun, Sandstorm to reposition.",
        "Epicenter without Blink, get interrupted during channel, Burrowstrike into 5 without team.",
        "Blink 12-14min. Epicenter + Blink timing is the hero's entire power spike.",
        "Early: offlane or mid, farm with Sandstorm+Caustic. Mid: Blink Epicenter teamfights. Late: initiate and control, Aghs for Sandstorm damage.",
    ),
    "Storm Spirit": (
        "Zip across the map with Ball Lightning, pick off heroes, snowball with mana items.",
        "Mana management, kill potential at level 6, Orchid/Kaya timing for pickoffs.",
        "Zip onto backline, Orchid silence + burst, Overload for damage between spells.",
        "Zip with no mana remaining, fight without mana items, ignore BKB timing.",
        "Orchid/Kaya 14-16min for kill potential. BKB 22-24min. Bloodstone for sustain.",
        "Early: farm mid, hit level 6 power spike. Mid: zip ganks across map, snowball. Late: pick-off machine, initiate on key targets.",
    ),
    "Sven": (
        "Cleave entire teams with God's Strength, Storm Hammer stun, Warcry armor/speed.",
        "BKB for uninterrupted hits, farm speed with cleave, God's Strength uptime in fights.",
        "BKB+God's Strength, Storm Hammer to initiate/stun, cleave through the whole team.",
        "Fight without God's Strength, get kited without BKB, Storm Hammer from max range and miss.",
        "Echo Sabre 12-14min, BKB 18-20min, Daedalus 26-28min for one-shot potential.",
        "Early: farm safe lane with cleave. Mid: God's Strength fights, take Roshan. Late: one-shot teams with crit+cleave.",
    ),
    "Tiny": (
        "Burst combo with Avalanche+Toss, flex pick (mid/offlane/support), grow into building destroyer.",
        "Combo execution, Blink for initiation, flex draft advantage. Tree Grab for cleave damage.",
        "Avalanche+Toss combo for burst, Blink initiation, right-click with Grow bonus damage.",
        "Toss allies into enemies accidentally, miss Avalanche timing with Toss, fight without Tree.",
        "Blink 12-14min (core) or 18-20min (support). Echo Sabre for attack speed.",
        "Early: burst kill potential at level 3 with combo. Mid: Blink ganks, push towers. Late: building destroyer, high physical damage.",
    ),
    "Vengeful Spirit": (
        "Swap saves or initiates, Wave of Terror armor reduce, Magic Missile stun, Vengeance Aura damage.",
        "Swap positioning (save carry or swap enemy in), aura value, stun follow-up.",
        "Swap enemy carry into team or save allied carry, stun priority targets, armor reduce with Wave.",
        "Swap yourself into 5 enemies, waste Magic Missile on creeps, position too far from carry.",
        "Force Staff 14-16min for double save (swap+force). Aghs for Swap range.",
        "Early: lane harass with Wave, stun for kills. Mid: smoke ganks, Swap pickoffs. Late: save carry with Swap, aura value.",
    ),
    "Windranger": (
        "Shackle for long stuns, Focus Fire to melt single targets, Powershot for harass/wave clear.",
        "Shackle angles (latch to tree/unit), Focus Fire target priority, Windrun for survival.",
        "Shackle priority targets, Focus Fire the carry, Windrun to dodge right-clicks.",
        "Shackle without latch target, Focus Fire tanks, forget Powershot for scouting.",
        "Javelin/Maelstrom 12-14min for Focus Fire damage. MKB for scaling.",
        "Early: harass with Powershot, Shackle kills. Mid: pick-offs with Shackle+Focus Fire. Late: burst single targets, evasion with Windrun.",
    ),
    "Zeus": (
        "Global burst with Thundergod's Wrath, Arc Lightning for lane/farm, Bolt for damage+vision.",
        "Mana sustain, positioning (squishy), level advantage for burst potential.",
        "Stay back, spam Bolt+Arc Lightning, Wrath to finish low heroes or initiate fights.",
        "Walk forward in fights, skip Aether Lens/mobility, Wrath on full HP enemies.",
        "Aether Lens 12-14min, Aghs 22-25min for Nimbus. Refresher for double Wrath.",
        "Early: dominate mid with Arc Lightning spam. Mid: gank with Bolt, global Wrath kills. Late: Nimbus+Refresher teamfight dominance.",
    ),
    "Kunkka": (
        "Cleave with Tidebringer, X Marks setup into Torrent+Ghost Ship combo, Rum buff for team.",
        "X Marks combo execution, Tidebringer last-hit harass, Ghost Ship accuracy.",
        "X+Torrent+Ship combo, Rum buff allies, Tidebringer cleave in fights.",
        "Miss X combo, waste Tidebringer on creeps during fights, Ship without setup.",
        "Armlet 10-12min or Radiance 16-18min. Daedalus for Tidebringer one-shots.",
        "Early: Tidebringer harass in lane. Mid: X combo pickoffs, push with team. Late: Tidebringer cleave carries fights, Rum saves team.",
    ),
    "Lina": (
        "High burst magic/pure damage, Fiery Soul attack speed stacks, Laguna Blade to delete heroes.",
        "Spell combos for Fiery Soul stacks, LSA stun accuracy, mana management.",
        "Chain stun with LSA, stack Fiery Soul, Laguna Blade to finish, right-click with stacks.",
        "Miss LSA, Laguna when target has too much HP, fight without Fiery Soul stacks.",
        "Eul's 12min for LSA setup. Aghs for pure Laguna. BKB 18-20min.",
        "Early: dominate mid, nuke waves. Mid: Eul's combo kills, push towers. Late: burst caster or right-click hybrid with Fiery Soul.",
    ),
    "Lion": (
        "Chain disable with Earth Spike + Hex, Finger of Death burst, Mana Drain sustain.",
        "Blink for initiation, chain stun execution, Finger kill stacks for damage.",
        "Blink+Spike+Hex chain disable, Finger priority target, Mana Drain between spells.",
        "Finger tanky heroes, Hex before Spike (wrong order), position too forward.",
        "Blink 16-18min. Aether Lens for catch range. Aghs Shard for AoE Spike.",
        "Early: roam with double disable, set up kills. Mid: Blink catches, Finger kills. Late: disable chain, save Finger for key target.",
    ),
    "Shadow Shaman": (
        "Push towers with Serpent Wards, Shackle lockdown, Hex disable, Ether Shock nuke.",
        "Shackle channel positioning, Ward placement on buildings, disable chain.",
        "Hex+Shackle chain disable, drop Wards on towers/in fights, Ether Shock for AoE.",
        "Wards in open field, Shackle without vision, get interrupted during Shackle.",
        "Blink 16-18min for initiation. Aghs for Wards on shorter CD. Refresher for double Wards.",
        "Early: push lane with Ether Shock, disable for kills. Mid: Ward push towers aggressively. Late: Refresher double Ward siege.",
    ),
    "Slardar": (
        "Amplify damage with Corrosive Haze (armor reduction), Blink+Crush initiation, bash with Bash of the Deep.",
        "Blink timing, Haze on priority physical damage targets, Sprint for mobility.",
        "Blink+Crush stun, Haze enemy carry for armor reduction, bash with attacks.",
        "Haze magic damage heroes, Crush without follow-up, Sprint into danger without Blink.",
        "Blink 10-12min, BKB 18-20min. Haze is the key value — apply it early in fights.",
        "Early: offlane with bash harass. Mid: Blink initiation, Haze for Roshan. Late: reliable initiator, Haze amplifies team's physical damage.",
    ),
    "Tidehunter": (
        "Ravage is one of the best teamfight ults, Kraken Shell removes debuffs, Anchor Smash reduces damage.",
        "Blink for multi-hero Ravage, survive lane, Anchor Smash damage reduction.",
        "Blink+Ravage on 3+ heroes, Anchor Smash to reduce enemy carry damage, tank with Kraken Shell.",
        "Ravage one hero, waste Ravage when team can't follow up, skip Blink.",
        "Blink 14-16min, Refresher 28-30min for double Ravage. Ravage timing wins games.",
        "Early: survive offlane, Anchor Smash to farm. Mid: Blink Ravage teamfights. Late: Refresher double Ravage, frontline tank.",
    ),
    "Witch Doctor": (
        "Maledict amplifies burst damage, Death Ward channels massive DPS, Paralyzing Cask bounces.",
        "Maledict timing (before burst), Death Ward positioning, Cask bounces in small groups.",
        "Cask to stun, Maledict before team bursts, Death Ward from safe position/fog.",
        "Death Ward in open (get stunned), Maledict after damage is done, Cask into creep waves.",
        "Glimmer Cape 14-16min for safe Death Ward. Aghs for Death Ward bounce.",
        "Early: harass with Cask+Maledict, kill pressure. Mid: Maledict+team burst, Death Ward fights. Late: Glimmer+BKB Death Ward, Maledict priority targets.",
    ),
    "Lich": (
        "Chain Frost bounces devastate grouped enemies, Frost Blast slow, Frost Shield damage reduction.",
        "Chain Frost targeting (bounces need grouped enemies), Frost Shield on right ally, lane dominance.",
        "Frost Shield your frontliner, Chain Frost into grouped enemies, Blast to slow.",
        "Chain Frost into single target, Frost Shield too late, skip Sinister Gaze.",
        "Glimmer/Force 14-16min for saves. Chain Frost at level 6 is huge power spike.",
        "Early: dominate lane with nukes, zone enemy. Mid: Chain Frost teamfights. Late: Frost Shield carry, Chain Frost grouped fights.",
    ),
    "Riki": (
        "Permanent invisibility, Smoke Screen silence+miss, Tricks of the Trade AoE backstab.",
        "Target selection (kill supports), Smoke Screen placement, Diffusal for slow+mana burn.",
        "Smoke Screen enemy carry, backstab supports, Tricks of the Trade to dodge and AoE damage.",
        "Fight into detection, Smoke Screen wrong targets, roam without Diffusal.",
        "Diffusal 14-16min for kill potential. BKB 22-24min to fight into detection.",
        "Early: roam and backstab, scout with invis. Mid: pickoffs with Smoke+Diffusal. Late: Tricks of the Trade teamfight, target backline.",
    ),
    "Enigma": (
        "Black Hole is the most powerful teamfight ult, Eidolons push and farm, Midnight Pulse %HP damage.",
        "Blink for Black Hole, don't get interrupted, Eidolon micro for farm.",
        "Blink+Midnight Pulse+Black Hole combo on 2+ heroes. Eidolons for extra damage.",
        "Black Hole one hero, get stunned during channel, lose Eidolons to AoE.",
        "Blink 12-14min (jungle farm), BKB 20-22min for uninterrupted Black Hole. Refresher for double Hole.",
        "Early: jungle with Eidolons, push lanes. Mid: Blink Black Hole, take objectives. Late: BKB Black Hole, Refresher for insurance.",
    ),
    "Tinker": (
        "Infinite spell spam with Rearm, global presence with BoTs, Defense Matrix for ally saves.",
        "Mana management, BoTs timing, Laser+Missile+Rearm combo execution, map awareness.",
        "Stay far back, spam Laser+Missile+Rearm, Defense Matrix key ally, BoTs to split push.",
        "March into dangerous areas, Rearm without mana, BoTs to wrong lane, get caught between Rearms.",
        "BoTs 10-12min, Blink 16-18min, Overwhelming Blink for burst.",
        "Early: farm mid with Laser+Missile. Mid: BoTs ganks, split push. Late: perma-push lanes, spam from distance.",
    ),
    "Sniper": (
        "Longest attack range in game, Headshot mini-stun harass, Assassinate for finishing kills.",
        "Positioning (no escape), team protection, Shrapnel for vision/slow/damage.",
        "Stay max range, Shrapnel for zone control, Headshot procs, Assassinate low HP heroes.",
        "Position forward, skip Hurricane Pike (no escape), fight without vision.",
        "Dragon Lance 10-12min, Pike 14-16min, Maelstrom/Mjollnir for farm.",
        "Early: harass with range advantage. Mid: siege towers with Shrapnel, Take Aim range. Late: glass cannon, needs team to frontline.",
    ),
    "Necrophos": (
        "Reaper's Scythe kills add to death timer, sustain with Death Pulse, Ghost Shroud for magic heal amp.",
        "Stay alive in fights (Heart/tanky), Scythe timing (% HP threshold), Ghost Shroud timing.",
        "Stay in the fight healing with Pulse, Ghost Shroud for burst survival, Scythe to extend death timers.",
        "Scythe full HP heroes, Ghost Shroud against magic damage, skip Radiance timing.",
        "Radiance 16-18min for sustain fights. Holy Locket or Heart for tankiness.",
        "Early: win lane with Death Pulse sustain. Mid: push with Radiance, extended fights favor you. Late: Scythe key heroes, death timer wins.",
    ),
    "Warlock": (
        "Fatal Bonds spreads damage across enemies, Chaotic Offering stuns with Golem, Shadow Word heal/damage.",
        "Fatal Bonds before team damage, Golem placement, Shadow Word timing.",
        "Fatal Bonds 3+ heroes, Golem stun into AoE, Shadow Word heal carry or damage priority.",
        "Golem without Fatal Bonds, Shadow Word wrong target, Bonds on single target.",
        "Aghs 25-28min for double Golem. Refresher for quad Golem. Holy Locket for heals.",
        "Early: sustain lane with Shadow Word, harass with Bonds. Mid: Fatal Bonds teamfights, Golem stun. Late: Refresher Golem army.",
    ),
    "Beastmaster": (
        "Roar is BKB-piercing lockdown, summons provide vision/push, Inner Beast attack speed aura.",
        "Roar on priority target, Hawk vision, Boar slow for ganks, push with summons.",
        "Roar enemy carry through BKB, summons in fights for DPS/scouting, Wild Axes for stacks.",
        "Roar supports, lose summons to AoE, skip Hawk scouting.",
        "Helm of the Overlord 16-18min for dominated creep, Aghs Shard. Blink or Drums first.",
        "Early: offlane push with summons, Hawk vision. Mid: Roar pickoffs, push towers. Late: BKB-piercing Roar wins fights.",
    ),
    "Queen of Pain": (
        "Blink for mobility, Scream+Sonic Wave burst, snowball with early kills.",
        "Blink aggressive+defensive use, combo execution, early kill potential.",
        "Blink in, Scream+Wave combo, Blink out. Shadow Strike to slow runners.",
        "Blink into 5 heroes, Wave on single target, fight without Blink cooldown.",
        "Orchid 14-16min for solo kills. Aghs for pure Wave damage. BKB when needed.",
        "Early: dominate mid with Scream, Blink at 6. Mid: Orchid pickoffs, Wave teamfights. Late: burst damage, Blink mobility.",
    ),
    "Venomancer": (
        "DoT damage everywhere — Poison Nova, Plague Wards for vision/push, Gale for slow.",
        "Ward placement for vision/push, Gale accuracy, Poison Nova timing.",
        "Poison Nova in teamfight, Gale to slow, Wards for DPS. Everything stacks poison.",
        "Wards in useless spots, Nova on 1 hero, fight without Wards pre-placed.",
        "Veil 12-14min for magic amp. Aghs for Poison Nova damage. Spirit Vessel synergy.",
        "Early: zone with Plague Wards, Gale harass. Mid: push towers with Wards, Nova fights. Late: massive DoT teamfighter.",
    ),
    "Faceless Void": (
        "Chronosphere traps enemies for team follow-up, Time Walk undoes damage, bash with Time Lock.",
        "Chrono placement (don't trap allies), Time Walk timing, farm speed.",
        "Chrono 2-3 enemies without allies, Time Walk to dodge burst, bash targets in Chrono.",
        "Chrono allies, Chrono one hero, Time Walk before taking damage (too early), fight without Chrono.",
        "Maelstrom 13-15min, BKB if needed. Chrono fights every 2min are your timing.",
        "Early: farm safe lane, Time Walk for survival. Mid: Chrono teamfights with team follow-up. Late: 5-man Chrono wins games.",
    ),
    "Wraith King": (
        "Two lives with Reincarnation, reliable stun, crit for damage, skeletons for push.",
        "Mana for Reincarnation (get mana burned = dead), farm speed, Radiance timing.",
        "Walk at enemies, stun priority target, Reincarnation slow after second life.",
        "Get mana burned/drained before dying, fight without Reincarnation mana, skip BKB.",
        "Radiance 16-18min or Armlet 10-12min. Blink for initiation.",
        "Early: farm safe lane, Skeleton harass. Mid: Radiance farm, push with skeletons. Late: unkillable frontline, Reincarnation forces enemy to fight twice.",
    ),
    "Death Prophet": (
        "Exorcism spirits melt towers and heroes, Spirit Siphon sustain, Silence for area denial.",
        "Exorcism uptime in fights, Spirit Siphon targets, push timing with Exorcism.",
        "Pop Exorcism, run at enemies, Spirit Siphon for sustain, Silence casters.",
        "Exorcism without a target (tower or fight), Spirit Siphon max range, fight when Exorcism on CD.",
        "Eul's 12-14min for setup/survival. Push towers immediately when Exorcism is up.",
        "Early: mid or offlane, Siphon sustain. Mid: Exorcism tower pushes, fight around ult CD. Late: Exorcism melts buildings and heroes.",
    ),
    "Phantom Assassin": (
        "Crit burst with Coup de Grace, Blink Strike for gap close, Blur for evasion, Stifling Dagger harass.",
        "BKB timing (MKB counters evasion), Desolator for early burst, snowball from kills.",
        "Blink Strike onto backline, crit burst supports/carries, Blur to dodge attacks.",
        "Fight into MKB carriers without BKB, crit relies on luck — need attack speed, skip Desolator.",
        "Desolator 14-16min for burst, BKB 20-22min. Battlefury for farm-oriented games.",
        "Early: Dagger harass in lane, last hit safely. Mid: Desolator burst pickoffs. Late: crit one-shots with Daedalus, need BKB+Satanic.",
    ),
    "Pugna": (
        "Nether Ward punishes spell-heavy teams, Life Drain sustain/damage, Decrepify amplifies magic.",
        "Nether Ward placement, Decrepify timing (friend or foe), Life Drain channel safety.",
        "Nether Ward before fight, Decrepify+Nether Blast combo, Life Drain to sustain or finish.",
        "Decrepify enemy physical carry (saves them from your carry), Ward in bad position, Life Drain without protection.",
        "Aether Lens 12-14min, Aghs for heal through Life Drain. Dagon for burst build.",
        "Early: push lane with Nether Blast. Mid: Nether Ward teamfights punish casters. Late: Life Drain sustain, Decrepify key targets.",
    ),
    "Templar Assassin": (
        "Meld strike armor reduction, Refraction damage block, Psi Blades spill, trap vision/slow.",
        "Refraction management, Meld positioning, farm speed for Desolator timing.",
        "Meld strike for armor reduction, Refraction for survival+damage, Psi Blade spill through targets.",
        "Fight with Refraction on cooldown, get DoT'd (removes charges fast), miss Meld strikes.",
        "Desolator 14-16min, Blink 20-22min for Meld Strike initiation. BKB when needed.",
        "Early: dominate mid with Refraction, deny+last hit. Mid: Desolator Roshan, burst pickoffs. Late: physical burst, Meld one-shots.",
    ),
    "Viper": (
        "Lane dominator, Nethertoxin breaks passives, Corrosive Skin punishes attackers, Viper Strike slows.",
        "Win lane hard, push advantage early, Nethertoxin placement for break.",
        "Nethertoxin break key passives, Viper Strike priority target, tank with Corrosive Skin.",
        "Lose lane (hero's entire purpose), skip push timing, let game go too late.",
        "Dragon Lance 10-12min, early Roshan with team. Falls off late — end by 30min.",
        "Early: dominate lane with Poison Attack. Mid: take towers, break passives with Nethertoxin. Late: falls off hard, end early.",
    ),
    "Luna": (
        "Lucent Beam bouncing ult, Moon Glaives for AoE farm/damage, Lunar Blessing aura.",
        "Farm speed, Eclipse single target or AoE burst, Moon Glaive for push.",
        "Eclipse isolated or small groups, Glaives bounce damage, Lucent Beam stun.",
        "Eclipse in creep waves, fight before items, skip BKB.",
        "Dragon Lance 10-12min, BKB+Manta 22-25min. Eclipse at 6 is strong kill potential.",
        "Early: farm fast with Glaives, Luna Blessing for lane. Mid: push with Glaives, Eclipse fights. Late: right-click carry with Glaive bounces.",
    ),
    "Dragon Knight": (
        "Dragon Form ranged splash for push, Breathe Fire damage reduction, natural tankiness with Dragon Blood.",
        "Dragon Form uptime for tower pushes, stun execution, tanky itemization.",
        "Dragon Form for splash + slow/DoT, stun priority target, frontline tank.",
        "Fight without Dragon Form, skip push timing, Dragon Tail out of range.",
        "Blink 12-14min for stun initiation. BKB 18-20min. Push towers during Dragon Form.",
        "Early: survive mid, Dragon Blood sustain. Mid: Dragon Form tower pushes. Late: tanky frontliner, Dragon Form splash damage.",
    ),
    "Dazzle": (
        "Shallow Grave prevents death, Shadow Wave heal+damage, Bad Juju armor reduction, Poison Touch slow.",
        "Grave timing (before ally dies), Shadow Wave positioning, armor reduction stacking.",
        "Grave carry when focused, Shadow Wave for AoE heal+damage, Bad Juju reduces armor over time.",
        "Late Grave (ally already dead), Shadow Wave without nearby units for bounce, waste Grave on yourself.",
        "Glimmer/Force 14-16min for saves. Solar Crest synergy with armor reduction.",
        "Early: lane harass with Poison Touch, sustain with Shadow Wave. Mid: Grave saves in fights. Late: Grave is game-changing, armor reduction scales.",
    ),
    "Clockwerk": (
        "Hookshot initiation, trap enemies in Power Cogs, Battery Assault in close range.",
        "Hookshot accuracy, Cog trapping (1v1 or cutting off), Battery Assault damage in Cogs.",
        "Hookshot into enemy, Cogs to trap, Battery Assault to interrupt channels and damage.",
        "Hookshot without team, Cogs trap allies, miss Hookshot, Battery Assault out of range.",
        "Blade Mail 12-14min, Force Staff to push out of Cogs. Aghs Shard for Overclocking.",
        "Early: offlane with Battery Assault kills, Rocket Flare to scout. Mid: Hookshot pickoffs. Late: Hookshot initiation, Blade Mail in Cogs.",
    ),
    "Leshrac": (
        "Pulse Nova AoE magic damage aura, Split Earth stun, Lightning Storm spam, tower demolisher.",
        "Mana sustain for Pulse Nova, Split Earth accuracy, survive being in the middle of fights.",
        "Pulse Nova + run at enemies, Split Earth stun, Lightning Storm spam for DPS.",
        "Pulse Nova without mana, Split Earth miss, stay at range (you need to be close).",
        "Bloodstone 16-18min for Pulse Nova sustain. BKB 20-22min. Travels for push.",
        "Early: push lane with Lightning, stun for kills. Mid: Pulse Nova team fights, push towers fast. Late: Bloodstone sustain, AoE damage machine.",
    ),
    "Nature's Prophet": (
        "Global presence with Teleportation, Sprout to trap, Wrath of Nature for global damage/farm.",
        "Teleport timing (don't TP into death), split push awareness, Sprout accuracy.",
        "Teleport to fights, Sprout key targets, Treants for push, Wrath of Nature for damage.",
        "TP into 5 heroes, AFK split push ignoring team, Sprout allies accidentally.",
        "Orchid 14-16min for ganks, or Gleipnir for teamfight. Aghs for Wrath bounce.",
        "Early: jungle+gank with TP, push lanes. Mid: global TP pressure, split push. Late: constant split push, TP to fights.",
    ),
    "Lifestealer": (
        "Built-in BKB with Rage, sustain with Feast lifesteal, Infest for surprise initiation.",
        "Rage timing, right-click damage items, Infest target selection.",
        "Rage through disables, Feast sustain in fights, Infest ally for surprise initiation.",
        "Rage preemptively, get kited (no gap close), fight without Feast sustain.",
        "Armlet 10-12min, Desolator/Basher 18-20min. Rage+Armlet toggle sustain.",
        "Early: farm safe lane, Feast sustain. Mid: Rage through stuns, fight with team. Late: BKB-piercing Rage, sustained fighter.",
    ),
    "Dark Seer": (
        "Vacuum+Wall combo, Ion Shell for lane/farm, Surge for speed boost.",
        "Vacuum+Wall timing, Ion Shell harass, Surge right target.",
        "Vacuum+Wall on grouped enemies (Wall copies), Ion Shell frontliners, Surge allies.",
        "Vacuum one hero, Wall without Vacuum, Ion Shell wrong target, fight without Vacuum.",
        "Blink 14-16min for Vacuum positioning. Mekansm/Pipe for team utility.",
        "Early: Ion Shell lane dominance, cut waves. Mid: Vacuum+Wall teamfights. Late: combo with team AoE, Surge saves.",
    ),
    "Clinkz": (
        "Invisible roaming ganker, Burning Barrage for burst, Death Pact for HP boost, Skeleton Walk for invis.",
        "Orchid/Gleipnir for lockdown, target selection (kill supports), map control with invis.",
        "Skeleton Walk to position, burst from invis, Burning Barrage for damage, Strafe for attack speed.",
        "Fight into detection without BKB, skip Orchid (no lockdown), team fight head-on.",
        "Orchid 14-16min or Gleipnir for AoE. Desolator for burst. BKB 22-24min.",
        "Early: harass with Searing Arrows, kill potential at 6. Mid: roam with invis, burst pickoffs. Late: split push, pick-off machine.",
    ),
    "Omniknight": (
        "Guardian Angel grants physical immunity, Purification burst heal+damage, Heavenly Grace dispel+status resist.",
        "Guardian Angel timing, Purification accuracy (centered on ally), Heavenly Grace before stuns.",
        "Guardian Angel when team is focused by physical, Purification heal+damage, Grace before disable.",
        "Late Guardian Angel, Purification miss (point blank AoE), Grace after ally is stunned.",
        "Holy Locket for heal amp, Soul Ring for mana. Guardian Angel timing wins fights.",
        "Early: sustain lane with Purification, Grace for saves. Mid: Guardian Angel teamfights. Late: save allies, Guardian Angel is game-changing.",
    ),
    "Enchantress": (
        "Enchant creeps for push/utility, Impetus pure damage scales with distance, Untouchable slows attackers.",
        "Enchant strong creeps (Centaur stun, Satyr purge), Impetus range management, kite with Untouchable.",
        "Impetus from max range, Enchant enemy summons, Untouchable makes you hard to right-click.",
        "Get burst by magic (Untouchable only helps vs attacks), fight close range, skip Holy Locket.",
        "Holy Locket 12-14min, Dragon Lance for Impetus range. Aghs for Impetus damage.",
        "Early: dominate lane with Enchant creeps, heal with Nature's Attendants. Mid: push with creeps, Impetus harass. Late: pure damage Impetus scaling.",
    ),
    "Huskar": (
        "Fight at low HP — Berserker's Blood gives attack speed and magic resist. Life Break initiates.",
        "Know HP threshold, Burning Spear stacking, Armlet toggling, BKB timing.",
        "Life Break the target you want to kill, Burning Spear stacks, tank with Berserker's Blood.",
        "Get bursted through Berserker's Blood (pure/physical), Life Break into 5, fight into AA ult.",
        "Armlet 8-10min, BKB 16-18min. Huskar's window is 10-25min — end before late game.",
        "Early: dominate lane, Burning Spear harass. Mid: snowball with Armlet, end game early. Late: falls off hard, end before 30min.",
    ),
    "Night Stalker": (
        "Nighttime powerhouse — bonus speed/damage at night, Void slow, Crippling Fear silence, Dark Ascension vision.",
        "Play around day/night cycle, Dark Ascension at night for flying vision, gap close.",
        "Void slow into Crippling Fear silence, Dark Ascension for vision+flying, run at targets at night.",
        "Fight during daytime (much weaker), waste Dark Ascension, skip BKB.",
        "Phase Boots + early gank items. BKB 16-18min. First night (5min) is crucial power spike.",
        "Early: dominate first night with ganks. Mid: Dark Ascension night fights, control vision. Late: silence+slow, night vision control.",
    ),
    "Broodmother": (
        "Lane dominator with spiders, web movement/invis, push lanes relentlessly.",
        "Spider micro (don't feed them), web placement, lane dominance, avoid AoE heroes.",
        "Push lanes with spiders, Insatiable Hunger for sustain/damage, webs for escape.",
        "Send spiders into AoE, pick Brood into AoE counters, leave webs without escape plan.",
        "Orchid 12-14min for kills, or Diffusal. Push timing is before enemy has AoE.",
        "Early: dominate lane, push tower with spiders. Mid: take map control with webs. Late: split push, create space.",
    ),
    "Bounty Hunter": (
        "Track for bonus gold, Jinada crit for burst, Shadow Walk for invis roaming.",
        "Track uptime in fights (gold advantage), Jinada timing, roam efficiency.",
        "Track all enemies in fights (bonus gold for team), Jinada burst, Shuriken Toss to finish.",
        "Forget to Track, fight without Shadow Walk escape plan, skip utility items.",
        "Spirit Vessel 12-14min or Solar Crest for utility. Track gold wins games economically.",
        "Early: roam with invis, Track kills for gold. Mid: Track in every fight, utility items. Late: Track gold advantage, Aghs Shuriken bounce.",
    ),
    "Weaver": (
        "Time Lapse undoes damage, Shukuchi for invis/speed/damage, Geminate Attack double hit.",
        "Time Lapse timing (survive burst in 5s window), Shukuchi weaving, Linken's for protection.",
        "Shukuchi in/out, Geminate Attack procs, Time Lapse when bursted, The Swarm armor reduce.",
        "Time Lapse too late (dead), fight without Shukuchi, skip Linken's (need it to Time Lapse).",
        "Maelstrom 12-14min, Linken's 16-18min. Desolator for burst with Geminate.",
        "Early: harass with Shukuchi+Geminate. Mid: pickoffs with Shukuchi, Time Lapse survival. Late: elusive carry, Time Lapse sustain.",
    ),
    "Jakiro": (
        "Dual Breath for slow/damage, Ice Path stun, Liquid Fire tower damage, Macropyre area denial.",
        "Ice Path accuracy, Liquid Fire on towers constantly, Macropyre placement.",
        "Ice Path stun followed by Dual Breath and Macropyre, Liquid Fire attack speed slow.",
        "Ice Path miss, Macropyre on moving targets (they walk out), skip Liquid Fire tower damage.",
        "Eul's 14-16min for Ice Path setup. Force Staff for saves.",
        "Early: push lane with Liquid Fire, harass. Mid: Ice Path + team follow-up, push towers. Late: Macropyre zone control, Ice Path stun.",
    ),
    "Batrider": (
        "Lasso drags enemies out of position (BKB-piercing), Sticky Napalm stacking damage, Flamebreak knockback.",
        "Blink Lasso execution, Napalm stacking, Lasso target priority.",
        "Blink+Lasso priority target, drag into team, Napalm stacks + Firefly for damage.",
        "Lasso without team, Lasso supports over carry, miss Napalm stacks, skip Blink.",
        "Blink 12-14min for Lasso, BKB 20-22min for safe Lasso. Force Staff to drag further.",
        "Early: Napalm harass in lane, Firefly farm. Mid: Blink Lasso pickoffs. Late: Lasso carry into team, BKB-piercing grab.",
    ),
    "Chen": (
        "Dominate jungle creeps for push/utility, global heal with Hand of God, send allies home with Holy Persuasion.",
        "Creep micro (use abilities), push timing, Hand of God global heal timing.",
        "Push with dominated creeps, Hand of God to save team globally, send low allies home.",
        "Lose creeps to AoE, skip pushing towers, Hand of God too late, bad creep selection.",
        "Mekansm 10-12min, push with creep army. Helm of the Overlord for ancient creeps.",
        "Early: dominate creeps, push tower with army. Mid: deathball push with team. Late: falls off, Hand of God saves.",
    ),
    "Spectre": (
        "Late game monster — Haunt to join fights globally, Desolate pure damage, Dispersion reflects damage.",
        "Farm until items, survive lane, team creates space, Haunt to join fights.",
        "Haunt into fights, Reality to right target, Desolate isolated targets, Dispersion tanks damage.",
        "Fight before Radiance, Haunt without team fighting, Reality wrong target.",
        "Radiance 18-22min, Manta 26-28min. Spectre is the HARDEST late game carry — don't end early.",
        "Early: survive lane, get farm. Mid: Haunt to join fights, Radiance farm. Late: unkillable carry with Dispersion+items.",
    ),
    "Ancient Apparition": (
        "Ice Blast prevents healing globally, Cold Feet stun setup, Chilling Touch for range.",
        "Ice Blast aim (global skillshot), Cold Feet stun setup (needs slow/stun), Vortex pull.",
        "Ice Blast into teamfight (no healing), Cold Feet after ally stuns, Vortex to hold.",
        "Ice Blast miss, Cold Feet without setup (they walk out), fight close range.",
        "Aghs 25-28min for longer Ice Blast. Force Staff/Glimmer for survival.",
        "Early: harass with Chilling Touch range, Cold Feet kills. Mid: global Ice Blast kills, anti-heal. Late: Ice Blast counters all healing lineups.",
    ),
    "Doom": (
        "Doom silences all abilities+items on one hero, Devour for creep abilities, Scorched Earth sustain.",
        "Doom target priority (shut down key hero), Devour good creep ability, Scorched Earth uptime.",
        "Doom their most important hero, Devour for utility abilities, Scorched Earth for chase/sustain.",
        "Doom supports over carry/mid, skip Devour ability, fight without Scorched Earth.",
        "Blink 14-16min for Doom initiation. BKB to prevent interruption. Shiva's for tank.",
        "Early: offlane with Devour gold, Scorched Earth harass. Mid: Doom pickoffs, push. Late: Doom their carry wins fights.",
    ),
    "Ursa": (
        "Fury Swipes stacking damage melts single targets, Overpower for attack speed burst, Enrage damage reduction.",
        "Gap close (Blink/Abyssal), Fury Swipes on single target, Enrage timing, early Roshan.",
        "Blink+Overpower+Fury Swipes burst, Enrage to survive burst, Earthshock slow.",
        "Get kited, fight multiple targets (single target hero), Enrage too late, skip Blink.",
        "Blink 12-14min, Basher/Abyssal 20-22min. Early Roshan with Fury Swipes is free.",
        "Early: dominate lane with Fury Swipes, solo Roshan. Mid: Blink burst kills. Late: Abyssal lock+Fury Swipes burst, Enrage sustain.",
    ),
    "Spirit Breaker": (
        "Global ganker with Charge of Darkness, bash through BKB, Nether Strike burst.",
        "Charge target selection, bash luck, team follow-up on Charge.",
        "Charge priority target across map, Greater Bash through BKB, Nether Strike for burst.",
        "Charge into 5 heroes, Charge without vision, skip Shadow Blade/BKB.",
        "Shadow Blade 12-14min for Charge+invis, BKB 18-20min. Charge ganks constantly.",
        "Early: roam with Charge ganks constantly. Mid: global presence, Charge picks. Late: BKB-piercing bash, Nether Strike burst.",
    ),
    "Gyrocopter": (
        "AoE teamfight with Flak Cannon+Call Down, Homing Missile stun, Rocket Barrage early damage.",
        "Flak Cannon item scaling, Call Down placement, Rocket Barrage close range.",
        "Flak Cannon hits everyone in range, Call Down for AoE slow, Homing Missile to stun.",
        "Rocket Barrage from far, Call Down on wrong spot, Flak Cannon without damage items.",
        "Maelstrom 12-14min, BKB 18-20min. Flak Cannon with items is the scaling mechanic.",
        "Early: Rocket Barrage kill potential, Homing Missile ganks. Mid: Flak Cannon fights. Late: AoE right-click carry with Flak.",
    ),
    "Alchemist": (
        "Farm fastest with Greevil's Greed, gift Aghs to allies, Chemical Rage regen tank.",
        "Radiance timing, Aghs gifting priority, Chemical Rage uptime.",
        "Chemical Rage before fighting, acid for armor reduction, Concoction stun, tank with regen.",
        "Fight without Chemical Rage, farm jungle ignoring lanes, gift Aghs before own core items.",
        "Radiance 13-15min, first Aghs gift 25min. BKB+AC for fights.",
        "Early: farm mid/safe with Greed, stack camps. Mid: Radiance farm, Chemical Rage fights. Late: 12-slotted with Aghs gifts, frontline tank.",
    ),
    "Invoker": (
        "10 spells with Quas/Wex/Exort combos, adapts to any situation, scales all game.",
        "Spell combo execution, Invoke timing, know when to use which spell.",
        "Tornado+EMP or Tornado+Meteor+Blast combo, Cold Snap for lockdown, Forge Spirits for DPS.",
        "Invoke wrong spell, miss Tornado/Sun Strike, use Deafening Blast without setup.",
        "Hand of Midas 8-10min (Exort), Blink 16-18min. Level 25 talent is huge power spike.",
        "Early: Sun Strike snipes (Exort) or Cold Snap ganks (Quas/Wex). Mid: combo teamfights. Late: all 10 spells, adapts to anything.",
    ),
    "Silencer": (
        "Global Silence stops all abilities, Intelligence steal on kills, Glaives pure damage.",
        "Global Silence timing (counter big ults), Arcane Curse for harass, Last Word silence.",
        "Global Silence to cancel enemy initiation/ults, Glaives for pure damage DPS.",
        "Global Silence too early (before enemy uses spells), waste Arcane Curse, position forward.",
        "Glimmer/Force 14-16min for utility. Refresher for double Global Silence.",
        "Early: harass with Glaives, steal INT on kills. Mid: Global Silence counters teamfight ults. Late: INT steal makes you stronger, double Silence.",
    ),
    "Outworld Destroyer": (
        "Sanity's Eclipse based on mana/INT difference, Astral Imprisonment for save/setup, Arcane Orb pure damage.",
        "Mana/INT stacking, Astral timing (save or offense), Arcane Orb for right-click damage.",
        "Arcane Orb for sustained pure damage, Astral to save ally or set up, Sanity's Eclipse for burst.",
        "Sanity's Eclipse when enemy INT is high, Astral at wrong time, run out of mana.",
        "Witch Blade/Meteor Hammer 12-14min, BKB 18-20min. Arcane Orb scales with INT items.",
        "Early: dominate mid with Arcane Orb, Astral harass. Mid: Sanity's Eclipse burst, BKB fights. Late: INT scaling carry, pure damage.",
    ),
    "Lycan": (
        "Push towers with summons, Shapeshift for max speed and crit, howl buff for team.",
        "Push timing with Shapeshift, summon management, Howl before fights.",
        "Shapeshift for unslowable chase, summons for DPS, Howl for team damage.",
        "Fight without Shapeshift, lose wolves to AoE, ignore push timing, go too late.",
        "Helm of the Overlord 14-16min, push during Shapeshift. Assault Cuirass for team push.",
        "Early: jungle with wolves, push lanes. Mid: Shapeshift tower pushes, end game fast. Late: falls off, needs to end early.",
    ),
    "Brewmaster": (
        "Primal Split into 3 elementals with stun/cyclone/dispel, Drunken Brawler crit/evasion.",
        "Primal Split micro (Cyclone key target, stun others), Blink initiation.",
        "Blink+Primal Split, Cyclone their carry, stun with Earth, Dispel with Storm.",
        "Skip Primal Split micro (just watch), let elementals die fast, miss Blink timing.",
        "Blink 12-14min, Aghs Shard. Primal Split fights every cooldown.",
        "Early: offlane with Brawler, Thunder Clap slow. Mid: Blink Primal Split teamfights. Late: Primal Split utility, Cyclone key targets.",
    ),
    "Shadow Demon": (
        "Disruption for save/setup+illusions, Demonic Purge slows+dispels, Soul Catcher damage amp.",
        "Disruption timing (save or offensive), Soul Catcher placement, Purge for dispel.",
        "Disruption saves allies or creates illusions of enemy carry, Soul Catcher to amp damage, Purge slows.",
        "Disruption at wrong time, Soul Catcher miss, Purge on wrong target.",
        "Glimmer/Force 14-16min. Aghs for 3 Purge charges. Aether Lens for range.",
        "Early: lane harass with Shadow Poison, Disruption saves. Mid: Disruption+Soul Catcher kills. Late: Disruption creates strong illusions of enemy carry.",
    ),
    "Lone Druid": (
        "Spirit Bear is a second hero with items, True Form for tankiness, Savage Roar fear.",
        "Bear micro (keep Bear alive), Bear item build, True Form toggling.",
        "Bear attacks with items, True Form for tank, Savage Roar to fear enemies away.",
        "Let Bear die (huge cooldown), fight without Bear nearby, skip Bear items.",
        "Mask of Madness on Bear 8-10min, Desolator 14-16min. Push towers with Bear.",
        "Early: Bear harass in lane, push tower. Mid: push with Bear items. Late: Bear is a full carry, True Form sustain.",
    ),
    "Chaos Knight": (
        "Phantasm illusions with full damage, Reality Rift pulls and reduces armor, Chaos Bolt stun.",
        "Phantasm timing (illusions are your DPS), Reality Rift to group on target, luck on Chaos Bolt.",
        "Phantasm then Reality Rift target into illusions, Chaos Bolt stun, overwhelm single target.",
        "Phantasm illusions die to AoE, fight without Phantasm, Reality Rift without illusions.",
        "Armlet 10-12min, Heart/Manta 22-25min. Phantasm fights are your timing.",
        "Early: Chaos Bolt kills in lane, farm. Mid: Phantasm burst kills, push towers. Late: illusion army overwhelms.",
    ),
    "Meepo": (
        "Multiple clones share XP, Poof for burst AoE/mobility, Earthbind root, Ransack lifesteal.",
        "Clone micro (all die if one dies), Poof combos, net accuracy, level advantage.",
        "Poof all Meepos together for burst, Earthbind roots, Ransack sustain, overwhelm with numbers.",
        "Lose one Meepo (all die), fight into AoE, skip Blink, get outleveled.",
        "Blink 10-12min (fast with clone XP), Aghs/Scythe for control. Level advantage IS the timing.",
        "Early: powerfarm with clones, hit 10+ by 10min. Mid: Poof ganks, push towers. Late: falls off vs AoE, end before 30min.",
    ),
    "Treant Protector": (
        "Living Armor global heal+block, Overgrowth roots entire team, Nature's Guise invis near trees.",
        "Living Armor timing, Overgrowth placement, tree manipulation with Eyes in the Forest.",
        "Overgrowth when enemy clumps, Living Armor allies globally, Nature's Guise for positioning.",
        "Late Living Armor, Overgrowth on one hero, forget Eyes in the Forest vision.",
        "Blink 16-18min for Overgrowth, or Meteor Hammer for push. Aghs for Eyes in the Forest map control.",
        "Early: roam with Nature's Guise, Living Armor saves globally. Mid: Overgrowth teamfights, heal towers. Late: Aghs map vision, Overgrowth roots.",
    ),
    "Ogre Magi": (
        "Multicast multiplies spells, Fireblast reliable stun, Ignite for slow/DoT, Bloodlust for ally buff.",
        "Bloodlust your carry, Fireblast priority targets, Ignite for chase, Multicast luck.",
        "Fireblast stun key target, Bloodlust your carry, Ignite slow fleeing enemies.",
        "Forget Bloodlust (huge buff), Fireblast wrong target, skip Ignite slow.",
        "Force Staff/Glimmer 14-16min, or Midas for levels. Aghs for Unrefined Fireblast.",
        "Early: zone with Ignite+Fireblast, tank with high armor/HP. Mid: Bloodlust carry, stun in fights. Late: Bloodlust value, Multicast burst.",
    ),
    "Undying": (
        "Decay steals STR, Tombstone spawns zombies that slow, Flesh Golem amps damage and heals.",
        "Decay stacking in lane, Tombstone placement, Flesh Golem timing.",
        "Tombstone in fights (hard to kill), Decay steal STR, Flesh Golem for amp/heal.",
        "Tombstone in bad position (gets killed), fight without Flesh Golem, skip Decay stacking.",
        "Holy Locket for heal amp, Mekansm for team. Tombstone fights are your power.",
        "Early: dominate lane with Decay STR steal. Mid: Tombstone teamfights, Flesh Golem push. Late: aura/utility hero, Tombstone placement wins fights.",
    ),
    "Rubick": (
        "Spell Steal copies enemy abilities, Telekinesis lift+throw, Fade Bolt damage reduction.",
        "Steal the RIGHT spell (game-changing), Telekinesis positioning, Fade Bolt in fights.",
        "Steal big ults (Ravage, Black Hole, RP), Telekinesis for setup, Fade Bolt damage reduction.",
        "Steal bad spells, Telekinesis without follow-up, miss timing on Spell Steal.",
        "Blink 16-18min for positioning, Aether Lens for Steal range. Aghs for instant Steal.",
        "Early: Fade Bolt harass, Telekinesis kills. Mid: Spell Steal key ults. Late: stolen ult wins fights, Blink+Steal.",
    ),
    "Disruptor": (
        "Glimpse sends enemies back, Static Storm silences+damage in area, Kinetic Field traps.",
        "Glimpse timing (send TP'd heroes back), Static Storm+Kinetic Field combo, Thunder Strike vision.",
        "Kinetic Field + Static Storm combo to trap and silence, Glimpse overextended enemies.",
        "Static Storm without Kinetic Field, Glimpse too late, Kinetic Field on wrong spot.",
        "Aghs 24-26min for mute on Static Storm. Glimmer/Force for survival.",
        "Early: Thunder Strike harass, Glimpse overextended enemies. Mid: Kinetic+Storm combo. Late: Aghs Static Storm mutes items, game-winning.",
    ),
    "Nyx Assassin": (
        "Vendetta invis burst, Spiked Carapace stun reflect, Impale stun, Mana Burn on INT heroes.",
        "Vendetta positioning, Carapace timing (reflect key spells), Impale accuracy.",
        "Vendetta from invis for burst, Carapace to reflect stuns, Impale for chain disable, Mana Burn casters.",
        "Carapace too early/late, Impale miss, Vendetta without team nearby.",
        "Aghs for Burrow (AoE Impale), Meteor Hammer combo, Aether Lens.",
        "Early: roam with Vendetta ganks. Mid: Carapace reflect key spells, Impale stuns. Late: Aghs Burrow for AoE stun, scout with Vendetta.",
    ),
    "Naga Siren": (
        "Illusion split push/farm, Song of the Siren for setup/disengage, Ensnare root, Riptide armor reduce. Illusions nerfed in 7.40.",
        "Illusion micro for split push, Song timing, farm speed. Diffusal no longer works on illusions — need stat-based build.",
        "Song to set up or disengage, illusions to push and scout, Ensnare key targets, Riptide armor reduce.",
        "Song at wrong time (save enemies), DO NOT buy Diffusal (mana burn no longer works on illusions), illusions die to AoE.",
        "Manta 18-20min, Heart/Butterfly 26-28min for illusion scaling. Song of the Siren regen nerfed too.",
        "Early: farm safe lane. Mid: split push with illusions, Song fights. Late: stat-heavy illusion army, weaker than previous patches.",
    ),
    "Keeper of the Light": (
        "Illuminate for wave clear, Chakra Magic for mana, Will-O-Wisp to blind, Blinding Light knockback.",
        "Illuminate charging, Chakra Magic on right ally, Will-O-Wisp placement.",
        "Will-O-Wisp in teamfight (enemies can't act when facing), Chakra key ally, Illuminate for damage.",
        "Illuminate without charging, Chakra yourself over carry, Will-O-Wisp destroyed instantly.",
        "Glimmer/Force 14-16min, Aghs for Illuminate heal. Solar Crest for utility.",
        "Early: Illuminate wave push, Chakra carry for sustain. Mid: Will-O-Wisp fights, push with Illuminate. Late: Chakra CD reduction for carry, Will-O-Wisp control.",
    ),
    "Io": (
        "Tether to ally for shared regen and relocate, Overcharge for attack speed, Spirits for damage.",
        "Tether target (stay with carry), Relocate timing (save or gank), Overcharge management.",
        "Tether carry, Overcharge for attack speed, Relocate for global ganks/saves.",
        "Break Tether, Relocate into 5 enemies, Overcharge without Tether partner.",
        "Holy Locket for heal amp, Mekansm for heal share. Io+carry combo is the timing.",
        "Early: lane with carry, Tether sustain. Mid: Relocate ganks across map. Late: keep carry alive with Tether+Overcharge.",
    ),
    "Visage": (
        "Familiars stun in AoE, Grave Chill slows, Gravekeeper's Cloak damage resist, Soul Assumption nuke.",
        "Familiar micro (stun+resummon), Soul Assumption stacks, Grave Chill targets.",
        "Familiar stuns, Soul Assumption burst, Grave Chill slow priority target.",
        "Familiars die without using stun, Soul Assumption without stacks, skip Familiar micro.",
        "Medallion/Solar Crest for armor reduce, Aghs for 3rd Familiar. Familiar stun resets are key.",
        "Early: dominate lane with Familiars, Soul Assumption burst. Mid: push towers with Familiars. Late: Familiar stuns in fights, Solar Crest buff carry.",
    ),
    "Slark": (
        "Essence Shift steals stats permanently per fight, Shadow Dance regen/invis, Pounce leash, Dark Pact purge.",
        "Dark Pact purge timing, Pounce accuracy, Shadow Dance to regen, steal stats in extended fights.",
        "Dark Pact purge debuffs, Pounce to leash, Shadow Dance to regen and go invis, steal stats over time.",
        "Fight short engagements (need time to steal stats), Pounce miss, Dark Pact when full HP.",
        "Diffusal 14-16min, BKB/Shadow Blade 18-20min. Slark loves long fights for stat steal.",
        "Early: farm safe lane, Pounce kills. Mid: pick-offs with Shadow Dance, snowball. Late: stat steal makes you a monster in long fights.",
    ),
    "Medusa": (
        "Hardest carry to kill — Mana Shield absorbs damage, Stone Gaze petrifies, Split Shot for AoE.",
        "Farm for items (very slow start), Mana Shield mana management, Stone Gaze timing.",
        "Stand in front with Mana Shield, Split Shot all enemies, Stone Gaze when enemies face you.",
        "Fight before items, Stone Gaze when enemies look away, run out of mana (Mana Shield drops).",
        "Manta 22-25min, Skadi 28-30min. Medusa needs 3+ items to fight.",
        "Early: farm, farm, farm. Mid: farm ancients+lanes with Split Shot. Late: unkillable with items, Stone Gaze wins fights.",
    ),
    "Troll Warlord": (
        "Battle Trance for max attack speed, switch melee/ranged, Whirling Axes for miss/slow, Fervor stacking.",
        "Battle Trance target (locks on), melee/ranged switching, Fervor stacks on single target.",
        "Battle Trance onto priority target, Fervor stack for DPS, Whirling Axes for utility.",
        "Battle Trance wrong target, switch forms unnecessarily, fight without Fervor stacks.",
        "BKB 16-18min, Diffusal/Basher 20-22min. Battle Trance + Roshan is easy.",
        "Early: lane with range form, switch melee for bash. Mid: Roshan with Battle Trance, fight. Late: sustained DPS carry, Battle Trance burst.",
    ),
    "Centaur Warrunner": (
        "Stampede global haste, Hoof Stomp stun, Double Edge nuke, Retaliate returns damage.",
        "Blink+Stomp initiation, Double Edge trade, Stampede timing for team.",
        "Blink+Stomp, Double Edge for burst, Stampede for team initiation or escape.",
        "Double Edge when low HP, Stomp miss, Stampede without team ready.",
        "Blink 12-14min, Pipe/Crimson for team utility. Stampede fights win games.",
        "Early: offlane tank, Retaliate punishes attackers. Mid: Blink Stomp initiation. Late: Stampede global mobility, frontline tank.",
    ),
    "Magnus": (
        "Reverse Polarity is game-winning AoE stun+pull, Empower for cleave buff, Skewer repositions.",
        "Blink+RP on multiple heroes, Empower your carry, Skewer accuracy.",
        "Blink+RP 3+ heroes, Empower carry for cleave, Skewer into team after RP.",
        "RP one hero, Empower wrong hero, Skewer into enemies without team.",
        "Blink 14-16min, BKB for RP, Refresher for double RP. Empower your carry at all stages.",
        "Early: Empower carry, farm with Shockwave. Mid: Blink RP teamfights. Late: Refresher double RP, Empower carry.",
    ),
    "Timbersaw": (
        "Pure damage nukes that cut trees, reactive armor for tankiness, Whirling Death STR reduce.",
        "Tree positioning for Timber Chain, reactive armor stacking, Chakram for sustained damage.",
        "Timber Chain through trees for mobility, Chakram for AoE pure damage, Whirling Death STR reduce.",
        "Fight without trees nearby, get silenced (can't cast), skip Bloodstone/Lotus.",
        "Bloodstone 14-16min for mana sustain, Lotus Orb for dispel. Kaya+Sange for tank.",
        "Early: dominate offlane with reactive armor + nukes. Mid: unkillable in trees, pure damage. Late: sustained pure damage, needs trees.",
    ),
    "Bristleback": (
        "Tank damage from behind with Bristleback passive, Quill Spray stacks, Viscous Nasal Goo armor reduce.",
        "Turn your back to damage, Quill stacks, Goo stacking, chase with Warpath stacks.",
        "Run at enemies with back turned, Quill Spray stacks, Goo for armor reduce, Warpath for speed/damage.",
        "Face enemies (take full damage), fight without Quill stacks, get kited without items.",
        "Vanguard 8-10min, Sange & Yasha 16-18min. Bristleback needs to snowball early.",
        "Early: tank lane with Bristleback passive, harass with Goo+Quills. Mid: run at people with Warpath. Late: needs items to not fall off.",
    ),
    "Tusk": (
        "Snowball to save allies or gank, Walrus Punch crit, Ice Shards to trap, Tag Team slow.",
        "Snowball saves (bring ally inside), Ice Shards placement, Walrus Punch timing.",
        "Snowball to save or initiate, Ice Shards to trap, Walrus Punch for burst, Tag Team slow.",
        "Snowball allies into danger, Ice Shards block ally escape, Walrus Punch early (waste crit).",
        "Blink/Shadow Blade 14-16min, Desolator for Walrus Punch burst. Solar Crest utility.",
        "Early: roam with Snowball ganks, Ice Shards kills. Mid: pickoffs with Walrus Punch. Late: save allies with Snowball, utility role.",
    ),
    "Skywrath Mage": (
        "Arcane Bolt spam, Ancient Seal silence+magic amp, Concussive Shot slow, Mystic Flare burst.",
        "Seal before Mystic Flare (magic amp), Flare on single isolated targets, mana management.",
        "Seal priority target, Mystic Flare when isolated, Bolt spam, Concussive for slow.",
        "Mystic Flare on grouped enemies (damage splits), Seal wrong target, run out of mana.",
        "Rod of Atos 12-14min for Mystic Flare setup. Aghs for longer Flare.",
        "Early: harass with Bolt spam, Seal for kills. Mid: Atos+Seal+Flare combo kills. Late: Seal+Flare on isolated targets.",
    ),
    "Abaddon": (
        "Aphotic Shield dispels and absorbs, Borrowed Time heals from damage, Mist Coil heal/nuke.",
        "Shield timing (instant dispel), Borrowed Time awareness, Mist Coil targets.",
        "Shield allies being stunned, Borrowed Time when focused, Mist Coil to heal or damage.",
        "Shield after ally dies, let Borrowed Time get dispelled, Mist Coil at wrong time.",
        "Holy Locket or Vlads 12-15min for sustain, Solar Crest for carry buff.",
        "Early: trade with Shield, zone with Mist Coil. Mid: save hero with Shield dispel, push. Late: Borrowed Time bait, Shield dispels.",
    ),
    "Elder Titan": (
        "Astral Spirit for damage+move speed, Echo Stomp sleep, Earth Splitter for %HP damage, Natural Order aura removes armor/magic resist.",
        "Echo Stomp setup, Astral Spirit management, Earth Splitter timing.",
        "Astral Spirit+Echo Stomp sleep, Earth Splitter on sleeping enemies, Natural Order aura in fights.",
        "Echo Stomp breaks immediately, Earth Splitter miss, Astral Spirit without return buff.",
        "Blink 16-18min for Stomp setup, Solar Crest for utility.",
        "Early: Astral Spirit harass, Echo Stomp ganks. Mid: Stomp+Splitter combo. Late: Natural Order armor/resist removal, Splitter %HP damage.",
    ),
    "Legion Commander": (
        "Duel locks two heroes in 1v1 (winner gets permanent damage), Overwhelming Odds nuke, Press the Attack dispel+heal.",
        "Duel target (must win), Blink+Duel execution, Press the Attack to save or buff.",
        "Blink+Duel weak target for guaranteed win, Press the Attack to dispel ally, Overwhelming Odds for damage.",
        "Duel tanky heroes you can't kill, Duel without team, feed Duel damage to enemy.",
        "Blink 12-14min, Blade Mail 10-12min for Duel safety, BKB 20-22min.",
        "Early: dominate offlane with Overwhelming Odds, jungle. Mid: Blink+Duel pickoffs, stack damage. Late: permanent damage stacking carry.",
    ),
    "Techies": (
        "Proximity Mines for area denial, Blast Off for AoE silence, Reactive Tazer for defense.",
        "Mine placement for zoning, Blast Off timing, Sticky Bomb slow.",
        "Mines for zone control, Blast Off for AoE silence, Sticky Bomb slow for chase.",
        "Mines in obvious spots, Blast Off into 5 enemies, skip mine defense.",
        "Eul's 12-14min for setup, Aether Lens for range. Aghs Shard.",
        "Early: mine rune spots, Blast Off kills. Mid: mine key areas, push with team. Late: mine high ground defense, zone control.",
    ),
    "Ember Spirit": (
        "Remnant for global mobility+escape, Sleight of Fist for safe AoE, Flame Guard shield, Searing Chains root.",
        "Remnant management (escape saved), Sleight+Chain combo, Flame Guard timing.",
        "Sleight of Fist for safe damage, Searing Chains to root, Remnant in/out, Flame Guard for absorption.",
        "Use all Remnants offensively (no escape), Chains miss, Flame Guard broken by magic burst.",
        "Maelstrom 14-16min for Sleight damage, or Radiance. BKB when needed.",
        "Early: Flame Guard harass, Chains kills. Mid: Remnant ganks, Sleight+items damage. Late: AoE damage with Sleight, global mobility.",
    ),
    "Earth Spirit": (
        "Roll for initiation, Magnetize DoT spreads, Boulder Smash stun, Geomagnetic Grip silence.",
        "Stone remnant management, Roll accuracy, Magnetize spreading, combo execution.",
        "Roll initiate, Smash stun, Grip silence, Magnetize and refresh with stones.",
        "Run out of stones, Roll into 5, Magnetize without stones to refresh.",
        "Spirit Vessel 12-14min, BKB 18-20min. Early roaming is the power spike.",
        "Early: roam with Roll+Smash+Grip combos. Mid: Magnetize teamfights, Vessel. Late: utility and initiation, Magnetize DoT.",
    ),
    "Underlord": (
        "Firestorm wave clear, Pit of Malice root, Atrophy Aura damage reduce+steal, Dark Rift global TP.",
        "Firestorm for lane push, Pit placement, Atrophy Aura stacking, Dark Rift timing.",
        "Firestorm for AoE, Pit to root grouped enemies, Atrophy steal damage, Dark Rift to save/relocate team.",
        "Dark Rift too late, Pit miss, Atrophy stacks wasted by dying.",
        "Pipe/Crimson 14-16min for team utility, Guardian Greaves for sustain.",
        "Early: dominate offlane with Firestorm, push waves. Mid: push with aura, Dark Rift splits. Late: aura tank, Dark Rift for team repositioning.",
    ),
    "Terrorblade": (
        "Metamorphosis ranged form for push/damage, Conjure Image illusions, Sunder HP swap, Reflection slow. Illusions heavily nerfed in 7.40 (damage reduced to 20-35%).",
        "Metamorphosis timing (push towers), illusion management, Sunder for survival. Dark Unity now gives 60% damage buff within 1200 range.",
        "Metamorphosis for ranged DPS, Sunder when low HP to heal, Reflection to slow. Keep illusions within 1200 range for Dark Unity bonus.",
        "Sunder too late (dead), Metamorphosis without target, illusions into AoE. Conjure Image damage significantly nerfed — don't rely on illusion DPS alone.",
        "Dragon Lance 10-12min, Skadi/Eye of Skadi 20-22min. Push towers during every Metamorphosis. Stat items over Diffusal.",
        "Early: farm with illusions (weaker now). Mid: Meta push towers, Sunder for survival. Late: ranged carry with Meta, Sunder clutch. Weaker illusion hero this patch.",
    ),
    "Phoenix": (
        "Supernova stun if egg survives, Fire Spirits attack speed slow, Icarus Dive for mobility, Sun Ray %HP.",
        "Supernova placement (egg must survive), Fire Spirits accuracy, Dive positioning.",
        "Fire Spirits slow attack speed, Sun Ray for %HP damage/heal, Supernova when focused.",
        "Supernova in open (egg killed), Fire Spirits miss, Dive into 5 without escape.",
        "Shiva's Guard for Supernova protection, Refresher for double Supernova. Vessel synergy.",
        "Early: offlane/support with Fire Spirits harass, Sun Ray sustain. Mid: Supernova teamfights. Late: Supernova+Refresher, Sun Ray %HP.",
    ),
    "Oracle": (
        "False Promise makes ally invisible and delays damage/healing, Purifying Flames heal, Fortune's End dispel.",
        "False Promise timing (all damage/heals resolved after), Flames+Fortune combo, Fate's Edict.",
        "False Promise carry when bursted, Purifying Flames for burst heal, Fortune's End for dispel.",
        "False Promise too late, Flames enemy without follow-up purge, Fate's Edict on wrong target.",
        "Glimmer Cape 14-16min, Holy Locket for heal amp during False Promise.",
        "Early: strong lane with Flames+Fortune combo. Mid: False Promise saves in fights. Late: False Promise is one of the best saves in the game.",
    ),
    "Winter Wyvern": (
        "Winter's Curse makes enemies attack their own ally, Cold Embrace freezes and heals, Arctic Burn for range/slow.",
        "Curse target selection (enemies attack the cursed ally), Cold Embrace timing, Arctic Burn poke.",
        "Curse their carry (team kills their own carry), Cold Embrace to save allies, Arctic Burn for slow.",
        "Curse when no enemies nearby to attack, Cold Embrace against magic burst (they still take magic damage), Splinter Blast wrong target.",
        "Glimmer/Force 14-16min. Aghs for longer Curse, Holy Locket for Embrace heal.",
        "Early: Arctic Burn harass, Splinter Blast push. Mid: Curse teamfight wins. Late: Curse is game-changing, Cold Embrace saves.",
    ),
    "Arc Warden": (
        "Tempest Double creates full copy of yourself+items, Spark Wraith for zone, Flux for slow, Magnetic Field evasion.",
        "Double management (use Double's items), Spark Wraith placement, Flux for 1v1.",
        "Send Double to fight, stay safe, Spark Wraith for zone, Flux isolated targets, Magnetic Field for evasion.",
        "Fight in person when Double can do it, Flux grouped enemies (purges when allies nearby), waste Double.",
        "Midas 6-8min (Double doubles Midas), Maelstrom, Travels for Double push.",
        "Early: mid farm, Flux harass. Mid: Double for pushing/fighting safely. Late: Double is a full second hero, split push and fight simultaneously.",
    ),
    "Monkey King": (
        "Wukong's Command creates soldier ring, Jingu Mastery stacks for lifesteal/damage, Tree Dance mobility, Boundless Strike crit.",
        "Jingu Mastery 4-hit proc, Wukong's Command placement, Tree Dance scouting.",
        "Jingu proc then Wukong's Command, Boundless Strike crit, Tree Dance for positioning.",
        "Wukong's Command miss, fight without Jingu stacks, Tree Dance predictably.",
        "Echo Sabre 12-14min for Jingu procs, Desolator/BKB. Jingu proc is your power spike.",
        "Early: Tree Dance ganks, Jingu burst in lane. Mid: Wukong fights, Boundless Strike. Late: Wukong Command teamfighter.",
    ),
    "Dark Willow": (
        "Bramble Maze for root, Shadow Realm for untargetable nuke, Terrorize for AoE fear, Bedlam for single target.",
        "Bramble placement, Shadow Realm timing, Terrorize from hidden position.",
        "Bramble Maze area denial, Shadow Realm burst, Terrorize fear into Bedlam DPS.",
        "Terrorize miss, Shadow Realm too early, Bramble in wrong spot.",
        "Eul's 12-14min for setup, Gleipnir for root. Blink for Terrorize positioning.",
        "Early: roam with Bramble+Shadow Realm burst. Mid: Terrorize teamfights. Late: Terrorize+Bedlam combo, Shadow Realm burst.",
    ),
    "Pangolier": (
        "Rolling Thunder bounces and stuns, Shield Crash damage reduction, Swashbuckle procs on-hit, Lucky Shot disarm.",
        "Rolling Thunder bouncing, Shield Crash timing, Swashbuckle+on-hit items.",
        "Rolling Thunder for AoE stuns (bounce off walls), Shield Crash for damage reduction, Swashbuckle for procs.",
        "Rolling Thunder in open (no walls to bounce), Shield Crash without enemies, miss Swashbuckle.",
        "Diffusal/Basher 14-16min for Swashbuckle procs, Blink for positioning.",
        "Early: offlane/mid with Swashbuckle+Shield Crash. Mid: Rolling Thunder teamfights. Late: Rolling Thunder stun chain, Swashbuckle on-hit scaling.",
    ),
    "Grimstroke": (
        "Soulbind links two enemies (spells hit both), Stroke of Fate for damage, Phantom's Embrace silence, Ink Swell stun.",
        "Soulbind target selection (link carry+support = double stun), Ink Swell timing.",
        "Soulbind two enemies then cast single-target spells on both, Ink Swell ally for AoE stun, Phantom silence.",
        "Soulbind isolated hero, Ink Swell without follow-up, Phantom on wrong target.",
        "Aether Lens 14-16min for range, Aghs for Ink Swell on Soulbound targets.",
        "Early: Stroke harass, Phantom silence kills. Mid: Soulbind combos with ally spells. Late: Soulbind doubles all single-target abilities.",
    ),
    "Hoodwink": (
        "Sharpshooter long range nuke+break, Acorn Shot bounces, Bushwhack tree stun, Scurry for evasion near trees.",
        "Bushwhack near trees for stun, Sharpshooter aim, Acorn Shot for harassment.",
        "Bushwhack stun near trees, Acorn Shot for damage, Sharpshooter to finish/break passives.",
        "Sharpshooter miss, Bushwhack without trees, fight in open away from trees.",
        "Gleipnir 16-18min for Bushwhack setup, or Maelstrom. Aghs for Decoy.",
        "Early: Acorn harass, Bushwhack kills. Mid: Sharpshooter snipes, Bushwhack ganks. Late: break passives with Sharpshooter, Acorn AoE.",
    ),
    "Void Spirit": (
        "Astral Step remnant dash, Dissimilate dodge, Resonant Pulse shield, Aether Remnant pull.",
        "Astral Step combos, Dissimilate timing (dodge spells), Resonant Pulse shield management.",
        "Astral Step in and out, Dissimilate to dodge key spell, Remnant for pull, Pulse for shield.",
        "Use all Astral Step charges offensively (no escape), Dissimilate too early, Pulse without enemies.",
        "Witch Blade/Orchid 12-14min, Aghs Shard. Eul's for setup.",
        "Early: dominate mid with Remnant+Pulse. Mid: Astral Step ganks, high mobility. Late: elusive burst damage, Astral Step in/out.",
    ),
    "Snapfire": (
        "Mortimer Kisses long range AoE, Firesnap Cookie ally jump+stun, Lil' Shredder for attack slow.",
        "Cookie targeting (jump ally or self for stun), Mortimer Kisses aim, Lil' Shredder timing.",
        "Cookie ally for initiation/save, Mortimer Kisses from distance, Lil' Shredder for DPS.",
        "Mortimer Kisses close range (can't aim), Cookie miss, Lil' Shredder wrong target.",
        "Force Staff/Glimmer 14-16min. Aghs for Gobble Up ally launch.",
        "Early: Cookie+Shredder kills in lane, harass. Mid: Mortimer Kisses teamfights. Late: utility save with Cookie, long range Kisses.",
    ),
    "Mars": (
        "Arena of Blood traps enemies, God's Rebuke AoE crit, Spear of Mars stun against wall/tree, Bulwark front block.",
        "Spear+wall stun, Arena placement, God's Rebuke crit, Bulwark direction.",
        "Spear into Arena wall stun, Arena traps enemies, God's Rebuke for AoE crit damage, Bulwark to tank.",
        "Spear without wall behind target, Arena in open (enemies walk through sides), Bulwark wrong direction.",
        "Blink 12-14min for Spear+Arena combo, BKB 18-20min. Phase for God's Rebuke damage.",
        "Early: offlane with God's Rebuke harass, Spear stuns. Mid: Blink Arena fights. Late: Arena teamfight control, Spear pickoffs.",
    ),
    "Ringmaster": (
        "Wheel of Wonder for AoE debuffs, Escape Act for ally saves, Tame the Beasts for summon control.",
        "Escape Act timing, Wheel placement, team coordination.",
        "Escape Act to reposition allies, Wheel for teamfight control, Dark in the Spotlight for damage.",
        "Escape Act too late, Wheel on wrong area, poor Spotlight placement.",
        "Glimmer/Force for saves, Aether Lens for range.",
        "Early: lane harass, set up kills. Mid: team fight utility. Late: save allies with Escape Act, Wheel control.",
    ),
    "Dawnbreaker": (
        "Solar Guardian global TP+heal, Starbreaker AoE stun, Celestial Hammer slow, Luminosity heal on hits.",
        "Solar Guardian timing (global save/join fights), Starbreaker stun, Luminosity proc management.",
        "Solar Guardian to join fights globally, Starbreaker for AoE stun, Luminosity heals team with hits.",
        "Solar Guardian too late, Starbreaker miss, fight without Luminosity procs.",
        "Phase + Desolator or Echo Sabre 14-16min, BKB for Starbreaker.",
        "Early: offlane with Starbreaker damage, Hammer harass. Mid: Solar Guardian ganks globally. Late: frontline with Starbreaker, global presence.",
    ),
    "Marci": (
        "Dispose throw+stun, Rebound for mobility+stun, Sidekick for ally buff+lifesteal, Unleash for burst attack speed.",
        "Dispose targeting, Rebound positioning, Unleash timing, Sidekick right ally.",
        "Dispose throw enemy into allies, Rebound for gap close+stun, Unleash for burst DPS, Sidekick carry.",
        "Dispose wrong direction, Rebound without follow-up, Unleash without a target.",
        "BKB 16-18min for Unleash, Basher/Abyssal for lockdown. Desolator for burst.",
        "Early: roam with Dispose+Rebound combo. Mid: Unleash fights, snowball. Late: BKB Unleash burst, Dispose for pickoffs.",
    ),
    "Primal Beast": (
        "Pulverize BKB-piercing channel grab, Onslaught charge knockback, Trample AoE damage, Uproar stacking.",
        "Onslaught angle, Pulverize timing, Trample during Onslaught, Uproar stacks.",
        "Onslaught into Pulverize grab, Trample for AoE, Uproar for damage reduction stacks.",
        "Onslaught miss, Pulverize without team, get kited without Onslaught.",
        "BKB 14-16min for uninterrupted Pulverize, Blink for initiation.",
        "Early: offlane with Trample damage. Mid: Onslaught+Pulverize initiation. Late: BKB-piercing Pulverize, frontline tank.",
    ),
    "Muerta": (
        "Dead Shot ricochet fear, The Calling ghosts slow+silence, Pierce the Veil for magic immunity+ghost damage.",
        "Dead Shot angles for fear, Calling placement, Veil timing for immunity.",
        "Dead Shot fear into team, Calling zone control, Pierce the Veil for magic immunity DPS.",
        "Dead Shot without wall angle, Calling in wrong spot, Veil when no enemies near.",
        "Gleipnir/Maelstrom 14-16min, BKB/Aghs. Pierce the Veil at 6 is a strong spike.",
        "Early: Dead Shot harass, Calling zone control. Mid: Veil fights, Dead Shot fear picks. Late: Pierce the Veil physical immunity DPS.",
    ),
    "Kez": (
        "Shodo Slash for burst+mobility, Falcon Rush for gap close, Talon Toss for throw, Katana Blitz for rapid strikes.",
        "Combo execution, Shodo Slash positioning, Falcon Rush timing.",
        "Falcon Rush gap close, Shodo Slash burst, Talon Toss to reposition enemies, Katana Blitz for DPS.",
        "Shodo Slash without a target, fight without combo available, Falcon Rush into 5.",
        "Diffusal/Desolator 14-16min, BKB 20-22min for safe combos.",
        "Early: farm safe/mid, combo kills. Mid: burst pickoffs with full combo. Late: mobile burst carry.",
    ),
    "Largo": (
        "Long range artillery hero, Bombard for siege, Gargantuan for AoE stun, Vault for mobility.",
        "Bombard aim, Gargantuan timing, positioning at max range.",
        "Bombard from distance, Gargantuan for teamfight stun, stay at max range.",
        "Fight close range, Gargantuan miss, overextend without Vault escape.",
        "Maelstrom for farm, Pike for positioning. Plays like a siege hero.",
        "Early: lane with long range, harass. Mid: siege towers with range, Gargantuan fights. Late: artillery damage from distance.",
    ),
}


def build():
    output = {}
    for name, hero_id in sorted(name_to_id.items()):
        guide = GUIDES.get(name)
        if not guide:
            print(f"  SKIP {name}: no guide data")
            continue

        goal, requires, fights, dont, timings, gameStage = guide
        positions = get_positions(hero_id)
        if positions:
            pos_str = positions[0][1]
            pos_nums = [int(p[0]) for p in positions[:2]]
        else:
            pos_str = "Unknown"
            pos_nums = []

        output[name] = {
            "id": hero_id,
            "position": pos_str,
            "positionNumber": pos_nums,
            "goal": goal,
            "requires": requires,
            "fights": fights,
            "dont": dont,
            "timings": timings,
            "gameStage": gameStage,
        }

    out_path = ROOT / "data/RAG/RAG_content_heroes.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Wrote {len(output)} hero guides to {out_path}")


if __name__ == "__main__":
    build()
